### ISSUE TITLE
Author list formatting

### ISSUE THREAD

**Issue by tiffbogich** [scienceai/docx-standard-scientific-style#26]
Are we ok with the current recommendation for authors lists in ds3? (below)

- Authors
    - first author
    - shared first author
- Contributors
    - other author
    - other author
    - corresponding author <sup>*</sup>
- Affiliations
    - university 1
    - university 2

Or would we be better off having one list and letting the authors add footnotes directly below the author and affiliations sections (and above abstract), in the same way as table footnotes, not the built in footnotes) to allow for maximum flexibility on author labels (e.g. 4th and 5th author could also be equal contributors, but different from first and second author)?

- Authors
    - first author <sup>*</sup>
    - second author <sup>*</sup>
    - third author
    - fourth author<sup>&#167;</sup>
    - fifth author<sup>&#167;</sup>
    - sixth author <sup>&#450;</sup>
    - seventh author <sup>&#450;</sup>
- Affiliations
    - university 1
    - university 2

<sup>*</sup> Authors contributed equally
<sup>&#167;</sup> Authors contributed equally
<sup>&#450;</sup> Corresponding author

IMO one list is more natural for authors.  @darobin @sballesteros thoughts?

**Comment by darobin** [comment]
I prefer the first version if possible. It's a lot easier to parse. Part of my concern with the latter is how much microparsing has to happen to map things correctly (also, does the actual English sentence "Authors contributed equally" need to be present?). But if it's a show-stopper I can change the parser.

**Comment by tiffbogich** [comment]
Leaving as is.
