### ISSUE TITLE
various enhancements (clarifications)

### ISSUE THREAD

**Issue by sballesteros** [scienceai/docx-standard-scientific-style#33]
- [x] include typesetters feedback
- [x] add explanation on how to add caption for code
- [x] given that code and equation will have their own special description on how to add caption, maybe consider deleting "CREATE FIGURE AND TABLE CAPTIONS" section, and repeat it in the figure and table section, like that each section is self contained (standalone). I read the figure section, that's all I need (same for Code, Equation, Table...)
- [x] remove warning / suggestion potentially leading to incorrect english: (e.g  "Also, be sure to omit and '.' from organization and grant names and abbreviations (e.g. US Department of Homeland Security not U.S. Department of Homeland Security").

**Comment by tiffbogich** [comment]
## Typesetter feedback

### General 
- General Document and Formatting Warnings: 
    - check that document is saved as DOCX and not in 'compatibility mode'. If compatibility mode, covert document or start in a clean docx before proceeding
    - Omit line and page numbers, running head or running title, and article statistics (number of tables, figures, words, etc)
    - Omit author biographies, graphical abstracts, and tables of contents from main manuscript file
    - Add note on non standard section headings

### Figures and Tables
- Warning against putting figures inside tables (figures as figures and tables as tables) 
- Add to table footnotes: where to put table notes that don't have superscripts (e.g. everything in bold means p<0.05)
- Optional Note: Captions for special objects (e.g. Schemes)
    - same as supp figures and supp tables Add Label can be anything

### Author, Contributor, and Affiliation list
- Clarify: omit street address and postal code from affiliation information
- Clarify: instructions for finding a grid ID
- Clarify: instructions for finding an orcid ID
- Clarify: Add examples of how to identify a corresponding author 
- Clarify: Add examples of how to differentiate 'Authors' from 'Contributors' and default cases (e.g. first author listed = Author, all others = Contributors when no other instructions are provided)

### Abstract
- Clarify: Add specific note on structured abstract to ensure that subheadings are styled as H3 elements

### Funding
- Add: Funding information examples and how to infer funding sources from acknowledgments section
- Clarify: bibliography 
    - Format author list as LastName, First Middle; LastName2, First Middle; ...
    - if 'et al' at the end just leave as last in the list
    - delete periods after author initials and et al
    - set style to 'APA'
    - Add Warning: Ensure that section heading 'Bibliography' or 'Works Cited' is H2 not H1

**Comment by sballesteros** [comment]
> delete periods after author initials and et al 

If I understand correctly we can relax that see 

>  remove warning / suggestion potentially leading to incorrect english: (e.g "Also, be sure to omit and '.' from organization and grant names and abbreviations (e.g. US Department of Homeland Security not U.S. Department of Homeland Security").

above.
