### ISSUE TITLE
different types of abstracts

### ISSUE THREAD

**Issue by tiffbogich** [scienceai/docx-standard-scientific-style#48]
Recommendation is 'Type' + Abstract

Where type can be:
- graphical abstract
- lay abstract
- structured abstract

**Comment by transcranial** [comment]
A quick scan through pubmed central for abstract types:

- normal
- graphical
- precis
- short
- synopsis
- highlights
- editor highlights
- author highlights
- summary
- web summary
- editors summary
- editorial summary
- executive summary
- teaser
- key points

Structured abstracts isn't explicitly a "type" I can detect, but is inherent within the structure of the abstract element. I think

- normal
- graphical
- short
- structured
