### ISSUE TITLE
authors as organizations or groups

### ISSUE THREAD

**Issue by tiffbogich** [scienceai/docx-standard-scientific-style#54]
Probably best to handle in text rather than with another step. Perhaps If the author is an organization or a research group / consortium / collaboration (following same small -> large cascade of affiliation): 

```
<research group>, <department>,<organization> "<display name>" 
```

examples:
- ALICE Collaboration ([e.g.](http://arxiv.org/abs/1502.00230))
- International Human Genome Collaboration ([e.g](http://www.nature.com/nature/journal/v431/n7011/full/nature03001.html)) 

@leon is it possible to check for groups in author lists?

**Comment by sballesteros** [comment]
i think that's fine. It's just screen optimization. I think we can model that as a normal affiliation. You have 100 authors all affiliated to the consortium
the consortium is listed in the affiliation list.
Can just add a note in the affiliation definition that it can be a consortium, research group, social club, collaboration. 

I am working on refactoring the def of departement and org, will land that at that point

**Comment by tiffbogich** [comment]
## Examples with groups in the author lists:

- Olivieri I1, Cortesi PA2, de Portu S3, Salvarani C4, Cauli A5, Lubrano E6, Spadaro A7, Cantini F8, Ciampichini R2, Cutro MS9, Mathieu A5, Matucci-Cerinic M10, Punzi L11, Scarpa R12, Mantovani LG2; PACE Working Group. [http://www.ncbi.nlm.nih.gov/pubmed/26633622](http://www.ncbi.nlm.nih.gov/pubmed/26633622)
- Farruggia P1, Puccio G2, Sala A3, Todesco A4, Buffardi S5, Garaventa A6, Bottigliero G7, Bianchi M8, Zecca M9, Locatelli F10, Pession A11, Pillon M4, Favre C12, D'Amico S13, Provenzi M14, Trizzino A15, Zanazzo GA16, Sau A17, Santoro N18, Murgia G19, Casini T20, Mascarin M21, Burnelli R22; AIEOP (Italian Association of Pediatric Hematology and Oncology) and Hodgkin Lymphoma working group; AIEOP Italian Association of Pediatric Hematology and Oncology and Hodgkin Lymphoma working group. [http://www.ncbi.nlm.nih.gov/pubmed/26630532](http://www.ncbi.nlm.nih.gov/pubmed/26630532)
- Chinese XDR Consensus Working Group, Guan X1, He L2, Hu B2, Hu J3, Huang X4, Lai G5, Li Y6, Liu Y7, Ni Y8, Qiu H9, Shao Z10, Shi Y11, Wang M12, Wang R7, Wu D13, Xie C1, Xu Y14, Yang F15, Yu K16, Yu Y17, Zhang J15, Zhuo C6. [http://www.ncbi.nlm.nih.gov/pubmed/26627340](http://www.ncbi.nlm.nih.gov/pubmed/26627340)
