### ISSUE TITLE
Add section for entity styles

### ISSUE THREAD

**Issue by tiffbogich** [scienceai/docx-standard-scientific-style#61]
Some authors have applied bold styling to chemical entities in the set of sample documents.  Adding a new style for entities might help to separate 'strong' text from entity names.

Entity types (any missing?):
- genes
- proteins
- chemicals
- species
- diseases

@leon does this cover all the main entity types?  Do you think we need to create a different style for each entity type or just one 'entity' style and disambiguate from there? 

I will grab some more examples

**Comment by sballesteros** [comment]
the smallest number of entities the better, but I wonder if drugs could be worth it (or we can differentiate drugs easily). 
Could be good to look at cochrane review and see if they have recommendations for medical procedures and stuff like that

**Comment by transcranial** [comment]
IMO, if you're talking about styling, then I would recommend having one, so that it's not too restrictive. Specific entity type information can be encoded downstream.

**Comment by sballesteros** [comment]
but would it help to add semantic upstream or are our classifiers good enough to separate in between genes, proteins etc downstream?

**Comment by transcranial** [comment]
We can separate out genes, species, chemicals knowing a priori something's an 'entity' with 97-99% accuracy right now. Not knowing this a priori the problem becomes much harder. It's almost always the case that adding extra semantics upstream will help, but it's a balance between the amount of work you're adding and the benefit you get - and in this case, I don't think it's a lot. The biggest gain per unit of extra work, by far, is knowing that something is an 'entity' in the first place.

Also, wouldn't typesetters potentially need to be aware of the distinctions? I think that's a lot to ask of them.

**Comment by sballesteros** [comment]
Thanks a lot. Makes perfect sense. So 1 `Entity` style it is!
