### ISSUE TITLE
Funding format is not parseable

### ISSUE THREAD

**Issue by darobin** [scienceai/docx-standard-scientific-style#74]
The funding organisations are separated from the awards by a period. But period appear in things like `U.S.A.` or `Washington, D.C.`.

I tried the trick of splitting on a period followed by white space, but that trips over `U.S. Department of...`. Then I thought about doing that not followed by any `;` but it doesn't work either (there could be no award, or there could be a `;`-separated list of awards.

Possible fix: put the awards in italics?

**Comment by sballesteros** [comment]
Previously I was using the sbd module which is usually good enough for these things. I think it should still work fine but lmk otherwise

**Comment by darobin** [comment]
Funny, I was just telling @tiffbogich that I should give `sbd` a shot. I'll try that tomorrow. My concern is that we only have `sbd` for English. Given the context, I could also try just a heuristic to detect acronyms, but it would be pretty hairy due to JavaScript's lack of loookbehinds.

**Comment by darobin** [comment]
PS: you should come to party :)

**Comment by darobin** [comment]
Ok — went the `/`.
