### ISSUE TITLE
Resource Metadata and Credit Lines

### ISSUE THREAD

**Issue by sballesteros** [scienceai/docx-standard-scientific-style#75]
# Resource Metadata and Credit Lines

## Relevant schema.org properties for resource metadata

- [`author`](http://schema.org/author)
- [`contributor`](http://schema.org/contributor)
- [`licence`](http://schema.org/licence)
- [`copyrightHolder`](http://schema.org/copyrightHolder)
- [`copyrightYear`](http://schema.org/copyrightYear)
- [`provider`](http://schema.org/provider)
- [`citation`](http://schema.org/citation)
- [`exampleOfWork`](http://schema.org/exampleOfWork) -&gt; worth considering ?
- [`about`](http://schema.org/about)
- [`mention`](http://schema.org/mention) -&gt; worth considering ?
- [`isBasedOnUrl`](http://schema.org/isBasedOnUrl)
- [`citation`](http://schema.org/citation)
- [`sameAs`](http://schema.org/sameAs)

### Caption

- if caption contains references -&gt; `citation` (this is the only way to have citation for a resource)

### Authorship info

- Author and contributor **of the resource** (_not_ the work on top of which the resource is based on) -&gt; `author`, `contributor`
- License of the resource -&gt; `license`
- copyright of the resource (_not_ the work on top of which the resource is based on) -&gt; `copyrightYear`, `copyrightHolder`

### Credit lines

- Adapted [by permission] from: &lt;work&gt; [© &lt;copyrightYear&gt; &lt;copyrightHolder&gt;] -&gt; `isBasedOnUrl`
- Courtesy of: &lt;Person or Organization&gt;  -&gt; `provider` ?
- Data from: &lt;work&gt; [© &lt;copyrightYear&gt; &lt;copyrightHolder&gt;] -&gt; `isBasedOnUrl`
- Code from: &lt;work&gt; [© &lt;copyrightYear&gt; &lt;copyrightHolder&gt;] -&gt; `isBasedOnUrl`
- Reproduced [by permission] from: &lt;work&gt; [© &lt;copyrightYear&gt; &lt;copyrightHolder&gt;]  -&gt; `exampleOfWork`

permission is handled with `potentialAction` and `AuthorizeAction`

See https://www.elsevier.com/journals/critical-care-nursing-clinics-of-north-america/08995885/guide-for-authors

**Comment by tiffbogich** [comment]
Adding examples:

**[brb3362] (http://onlinelibrary.wiley.com/store/10.1002/brb3.362/asset/brb3362.pdf?v=1&t=ij3msfad&s=554a4dbc409429f85b241ae651624a88b774d497)**

Table 3. McDonald MRI criteria for demonstration of DIS (Polman
et al. 2011).
 
*in the table notes*
Based on Swanton et al. 2006, 2007. Adapted from Polman et al. (2011).

- Polman is referenced in the reference list, Swanton 2006 and 2007 are not.
- Table 3 in current article is exactly as written in Polman et al (2011, Table 1)
- Table 3 in current article and Table 1 in Polman are based on / adapted from Swanton et al. (2006 Table 1) and also Swanton et al. (2007 Table 1)
- Credit should be: Reproduced from Polman et al. (2011, Table 1); Adapted from Swanton et al. (2007, Table 1) and Swanton et al. (2006, Table 1).

**Comment by sballesteros** [comment]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3020576/figure/F11/
A benign cyst showing thin internal septation (arrows)on (A) radial and (B) antiradial ultrasonographic images in a 46-year-old woman. Often such cysts will be shown to communicate with each other if aspiration is attempted. (Courtesy of Wendie A. Berg, MD, PhD, Lutherville, MD.)

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1719771/pdf/v089p01084.pdf
Figure 4 (A) Dr Constance Peterson (Ingrid Bergman) psychoanalyses a patient in Spellbound (1945). (B) Prison psychiatrist (Sidney Poitier) treats a
racist Nazi psychopath prisoner (Bobby Darin) in Pressure Point (1962). (C) Dr Fritz Fassbinder (Peter Sellers) in What’s New, Pussycat (1965) takes
notes on his patient, Michael James (Peter O’Toole). (D) Dr Patch Adams (Robin Williams) plays with paediatric patients in Patch Adams (1998). All
photographs reproduced courtesy of the Academy of Motion Picture Arts and Sciences.

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1729609/figure/F2/
Multi-track technique: inflation of two balloons across the mitral valve—note the presence of one guidewire in the apex. Courtesy of Dr P Bonhoeffer.


http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2767298/figure/F1/
Organization of auditory cortex and connections. (a) Lateral brain schemata showing the location of auditory cortical areas in the macaque brain. (b) Magnified view of the primary auditory cortex, or core (purple) surrounded by the lateral and medial belt areas (yellow), which are bounded laterally by the parabelt cortex (orange). Connections between the core and belt areas are indicated. The progression of frequency tuning across an area is indicated by an “H” (high) or “L” (low). Projections to the cortex of the superior temporal sulcus (STS) and the prefrontal cortex are indicated with arrows. Diagram in (b) adapted from Hackett et al. 1998a.

**Comment by sballesteros** [comment]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4076293/figure/F1/

Fabricating micro/nanotopography in regular patterns
(a) Schematic of fabricating micro/nano-scale structures on a flat surface using soft lithography.[38] A PDMS stamp was used to mold the liquid precursor and was peeled off after the polymer was cured. (b) Schematic of fabricating micro/nano-scale features on curvilinear surfaces using soft lithography.[61] A pre-deformed PDMS stamp was used for generating the curvilinear surface, on which secondary micro/nano-scale features were molded. (c) SEM image of microtopography fabricated by soft lithography. Reproduced with permission from [38]. Copyright 2009, Nature Publishing Group. (d) SEM image of nano-scale surface structures fabricated by soft lithography, during which an h-PDMS/PDMS composite stamp was used to facilitate high geometrical fidelity. Reproduced with permission from [60]. Copyright 2002, American Chemical Society. (e) Schematic of the liquid-bridge-mediated nanotransfer moulding (LB-nTM).[63] A hard PDMS stamp loaded with nano-patterned foreign materials was put into contact with a thin liquid layer on the substrate. When evaporating the liquid, the meniscus facilitated the transfer of nano-molded materials onto the substrate. (f) SEM image of an array of zinc-tin oxide (ZTO) nanowires transferred onto silicon substrate using LB-nTM. Reproduced with permission from [63]. Copyright 2010, Nature Publishing Group.

**Comment by sballesteros** [comment]
Author(s): Person or Organization -> `author`
Contributor(s): Person or Organization -> `contributor`
License: License (SPDX) -> `license`
Copyright: © copyrightYear copyrightHolder -> `copyrightYear` `copyrightHolder`
Reproduced [by permission] from: Work [© copyrightYear copyrightHolder] -> `exampleOfWork`, `AuthorizeAction`
Adapted [by permission] from: Work [© copyrightYear copyrightHolder] -> `isBasedOnUrl`, `AuthorizeAction`
Data [by permission] from: Work [© copyrightYear copyrightHolder] -> `isBasedOnUrl`, `AuthorizeAction`
Code [by permission] from: Work [© copyrightYear copyrightHolder] -> `isBasedOnUrl`, `AuthorizeAction`
Code and Data [by permission] from: Work [© copyrightYear copyrightHolder] -> `isBasedOnUrl`, `AuthorizeAction`
Data and Code [by permission] from: Work [© copyrightYear copyrightHolder] -> `isBasedOnUrl`, `AuthorizeAction`
Courtesy of: Person or Organization -> `provider`
